build:
  environment:
    php:
      version: 7.1.4
      ini:
        'date.timezone': 'America/New_York'
  tests:
    override:
      -
        command: 'vendor/bin/phpunit'
        coverage:
          file: 'build/logs/clover.xml'
          format: 'php-clover'
filter:
  excluded_paths:
    - "tests/"
