<?php

use mindplay\middleman\Dispatcher;
use Zend\Diactoros\ServerRequestFactory;

/*
|--------------------------------------------------------------------------
| Autoloader.
|--------------------------------------------------------------------------
|
| Include the autoloader conveniently generated by composer.
|
*/

require_once __DIR__ . '/../vendor/autoload.php';

/*
|--------------------------------------------------------------------------
| Functions.
|--------------------------------------------------------------------------
|
| Include the required utility functions globally.
|
*/

require_once __DIR__ . '/../app/helpers.php';

/*
|--------------------------------------------------------------------------
| Middleware dispatcher.
|--------------------------------------------------------------------------
|
| Initializes a middleware dispatcher. Shortener currently uses the lovely
| Middleman (mindplay/middleman >= 3.0.0) package, however any PSR-15 compliant
| middleware dispatcher would be acceptable.
|
*/

$dispatcher = new Dispatcher(include __DIR__ . '/../middleware.php');

/*
|--------------------------------------------------------------------------
| PSR-7 Request.
|--------------------------------------------------------------------------
|
| Initialize a new PSR-7 HTTP request message from PHP's super globals.
| We then attach a new configuration attribute to be passed to all the
| middlewares.
|
*/

$request = ServerRequestFactory::fromGlobals()
    ->withAttribute('config', config());

/*
|--------------------------------------------------------------------------
| Middleware dispatch.
|--------------------------------------------------------------------------
|
| Now that we have our middleware stack loaded up with middleware, all we
| need to do is actually run through the stack. In the process we will
| initialize a new PSR-7 Request using the zend/diactoros package.
|
*/

$response = $dispatcher->dispatch($request);

/*
|--------------------------------------------------------------------------
| Emit the HTTP response.
|--------------------------------------------------------------------------
|
| We should now have a PSR-7 response from the middleware stack. The last
| step in the process is to output the response to the server in order to
| return an actual HTTP response to a client. To do this we are using
| another zend/diacotoros class.
|
*/

(new Zend\Diactoros\Response\SapiEmitter())->emit($response);
